/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminNotificationsRouteImport } from './routes/AdminNotifications'
import { Route as AddMessRouteImport } from './routes/add-mess'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as NutritionistRouteImport } from './routes/nutritionist'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SuperAdminRouteImport } from './routes/super-admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/AdminNotifications',
  path: '/AdminNotifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AddMessRoute = AddMessRouteImport.update({
  id: '/add-mess',
  path: '/add-mess',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionistRoute = NutritionistRouteImport.update({
  id: '/nutritionist',
  path: '/nutritionist',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AdminNotifications': typeof AdminNotificationsRoute
  '/add-mess': typeof AddMessRoute
  '/admin': typeof AdminRoute
  '/nutritionist': typeof NutritionistRoute
  '/privacy': typeof PrivacyRoute
  '/super-admin': typeof SuperAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AdminNotifications': typeof AdminNotificationsRoute
  '/add-mess': typeof AddMessRoute
  '/admin': typeof AdminRoute
  '/nutritionist': typeof NutritionistRoute
  '/privacy': typeof PrivacyRoute
  '/super-admin': typeof SuperAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/AdminNotifications': typeof AdminNotificationsRoute
  '/add-mess': typeof AddMessRoute
  '/admin': typeof AdminRoute
  '/nutritionist': typeof NutritionistRoute
  '/privacy': typeof PrivacyRoute
  '/super-admin': typeof SuperAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/AdminNotifications'
    | '/add-mess'
    | '/admin'
    | '/nutritionist'
    | '/privacy'
    | '/super-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/AdminNotifications'
    | '/add-mess'
    | '/admin'
    | '/nutritionist'
    | '/privacy'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/AdminNotifications'
    | '/add-mess'
    | '/admin'
    | '/nutritionist'
    | '/privacy'
    | '/super-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AddMessRoute: typeof AddMessRoute
  AdminRoute: typeof AdminRoute
  NutritionistRoute: typeof NutritionistRoute
  PrivacyRoute: typeof PrivacyRoute
  SuperAdminRoute: typeof SuperAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AdminNotifications': {
      id: '/AdminNotifications'
      path: '/AdminNotifications'
      fullPath: '/AdminNotifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-mess': {
      id: '/add-mess'
      path: '/add-mess'
      fullPath: '/add-mess'
      preLoaderRoute: typeof AddMessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutritionist': {
      id: '/nutritionist'
      path: '/nutritionist'
      fullPath: '/nutritionist'
      preLoaderRoute: typeof NutritionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AddMessRoute: AddMessRoute,
  AdminRoute: AdminRoute,
  NutritionistRoute: NutritionistRoute,
  PrivacyRoute: PrivacyRoute,
  SuperAdminRoute: SuperAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
